config/routes.rb
Rails.application.routes.draw do
  devise_for :users
    root to: "items#index"

# resources :routes, only: [:index, :show, :new, :create, :edit, :update, :destroy]

  resources :items do
    resources :trades, only: [:new, :create, :edit, :accept, :destroy]
  end
  resources :trades, only: [:destroy, :update]
  get '/dashboard', to: "items#dashboard"

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/item.rb
class Item < ApplicationRecord
  CATEGORIES = ["item", "electronics", "property", "food", "other"] #changed by AAG

  belongs_to :user
  has_one_attached :photo #added by AAG

  has_many :offered_trades, class_name: 'Trade', foreign_key: 'offered_item_id'
  has_many :requested_trades, class_name: 'Trade', foreign_key: 'requested_item_id'

  validates :name, presence: true
  validates :price, presence: true
  validates :description, presence: true
  # validates :photo, presence: true
  validates :category, presence: true

end
#, inclusion: { in: CATEGORIES }

app/models/trade.rb
class Trade < ApplicationRecord
  belongs_to :initiator, class_name: 'User'
  belongs_to :receiver, class_name: 'User'
  belongs_to :offered_item, class_name: 'Item'
  belongs_to :requested_item, class_name: 'Item'
end

app/models/user.rb
class User < ApplicationRecord

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :items, dependent: :destroy
  has_many :initiator_trades, class_name: 'Trade', foreign_key: 'initiator_id'
  has_many :receiver_trades, class_name: 'Trade', foreign_key: 'receiver_id'

  validates :email, presence: true, uniqueness: true
  validates :first_name, presence: true, uniqueness: true
  validates :last_name, presence: true, uniqueness: true
  # validates :profile_picture, presence: true

  # validates :movie, uniqueness: { scope: :list } #added by AAG as reminder
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  def configure_permitted_parameters
    # For additional fields in app/views/devise/registrations/new.html.erb
    devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name, :profile_picture])

    # For additional in app/views/devise/registrations/edit.html.erb
    devise_parameter_sanitizer.permit(:account_update, keys: [:first_name, :last_name, :profile_picture])
  end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_action :set_item, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [:index, :show]

  def dashboard
    @items = Item.all
    @trades = Trade.all
    if user_signed_in?
      @user_devise = current_user
      @items = Item.select( :user_id == current_user.id )

      @trades_incoming = Trade.select { |trade| trade.receiver_id == @user_devise.id}
      @trades_outgoing = Trade.select{ |trade| trade.initiator_id == @user_devise.id}
    end
  end

  def index
    @items = Item.all
    @user = current_user
    if params[:query].present? #search bar params
      @items = @items.where("name ILIKE ?", "%#{params[:query]}%")
    end
  end

  def show
    @trades = Trade.all
    @trade = Trade.new
  end

  def new
    @item = Item.new
  end

  def create
    if current_user
      @item = Item.new(item_params)
      @item.user = current_user
      if @item.save
        redirect_to item_path(@item)
      else
        redirect_to new_user_session_path, notice: 'You are not logged in.'
      end
    end
  end


  def edit
  end

  def update
    if @item.update(item_params)
      redirect_to item_path(@list)
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @item.destroy
    redirect_to items, status: :see_other
  end


  private

  def set_item
    @item = Item.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def item_params
    params.require(:item).permit(:name, :price, :description, :category, :title, :body, :photo) #:current_user
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController



end

app/controllers/trades_controller.rb
class TradesController < ApplicationController
  before_action :authenticate_user!

  def new
    @trade = Trade.new
  end

  def create
    if current_user
      @trade = Trade.new(trade_params)
      @trade.initiator = current_user
      @trade.offered_item = Item.find_by(id: params[:trade][:offered_item_id])
      @item = Item.find_by(id: params[:trade][:requested_item_id])
      @trade.requested_item = @item
      @trade.receiver = @item.user
      @trade.status = false
      if @trade.save
        # temporarily redirect to home
        # will redirect somewhere else when we have the profile page?
        redirect_to root_path
      else
        # if trade does not save
        render :new, status: :unprocessable_entity
      end
    end
  end

  def edit
    @trade = Trade.find(params[:id])
  end

  def update
    @trade = Trade.find(params[:id])
    @trade.status = !@trade.status
    if @trade.save
      redirect_to dashboard_path, notice: 'Trade status updated successfully.'
    else
      redirect_to dashboard_path, alert: 'Failed to update trade status.'
    end
  end

  def destroy
    @trade = Trade.find(params[:id])
    if @trade.destroy
      redirect_to dashboard_path, notice: 'Trade declined successfully.'
    else
      redirect_to dashboard_path, alert: 'Failed to update trade status.'
    end
  end

  private

  def trade_params
    params.require(:trade).permit(:initiator, :receiver, :offered_item, :requested_item)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/items/_itemform.html.erb
<div class="container">
  <h1>New Item</h1>

  <%= simple_form_for item do |f| %>
  <div class="raw main">
    <div class="col-5">
      <%= f.input :name %>
    </div>
    <div class="col-5">
      <%= f.input :price, hint: 'Prices should be in EUR' %>
    </div>
  </div>

  <div class="item-desc">
    <div class="col-11">
      <%= f.input :description, hint: 'Detailed descriptions work better' %>
    </div>
  </div>

  <div class="raw main">
    <div class="col-5">
      <%= f.input :category, hint: 'musical instruments, household items, electronics' %>
    </div>
    <div class="col-5">
      <%= f.input :photo, as: :file %>
    </div>
  </div>
  <div>
  <div style="margin-left:50px;"class="mt-3 ">
      <%= f.submit "Create new item", class: "btn btn-outline-primary" %>
  </div>
  <% end %>

  <div style="margin-left:50px;" class="mt-3">
    <%= link_to "go back to items", items_path %>
  </div>
</div>
</div>

app/views/items/dashboard.html.erb
<div class="container">
<%# displays title %>
  <div class="dashboard-titles">
    <h1>Incoming Trade Requests:</h1>
    <p>Accept or decline your incoming trade requests</p>
  </div>

<%# incoming trades %>
  <% if @trades_incoming %>
    <% @trades_incoming.each do |trade| %>
      <% if trade.status == false %>


      <% offer = @items.find(trade.offered_item_id) %>
      <% request = @items.find(trade.requested_item_id) %>
      <div class="flex-container profile-card">
        <div class="trade-item-image">
          <%= cl_image_tag request.photo.key, height: 300, width: 400, crop: :fill, class: "photo" %>
        </div>
        <div class="middle-container">
          <div class="trade-text text-box"><h5>Your <%= request.name %> for <%= offer.user.first_name %>'s <%= offer.name %></h5>
          </div>
          <%# buttons container %>
            <div class="button-container">
          <%# accept button %>

            <%= simple_form_for [@item, trade] do |f| %>
              <%= f.hidden_field :status, value: !trade.status %>
              <%= f.submit "Accept Trade", class: 'btn btn-outline-primary' %>
            <% end %>

              <%# decline button %>
            <%= simple_form_for [@item, trade], method: :delete do |f| %>
              <%= f.submit "Decline Trade", class: 'btn btn-outline-danger' %>
            <% end %>
              <%# <%= button_to 'Decline Trade', item_trade_path(@item.id, trade), turbo_method: :delete, class: 'btn btn-outline-danger', data: { turbo_confirm: 'Are you sure you want to decline this trade?' } %>
            </div>
          </div>

          <%# offer item %>
          <div class="trade-item-image">
            <%= cl_image_tag offer.photo.key, height: 300, width: 400, crop: :fill, class: "photo" %>
          </div>
        </div>
      <% end %>
    <% end %>
  <% end %>

<%# outgoing trade requests %>

  <div class="dashboard-titles">
    <h1>Outgoing Trade Requests:</h1>
    <p>Wait for your outgoing trade requests to be accepted</p>
  </div>


    <% if @trades_outgoing %>
      <% @trades_outgoing.each do |trade| %>
        <% request = @items.find(trade.offered_item_id) %>
        <% offer = @items.find(trade.requested_item_id) %>
        <div class="flex-container profile-card">
          <div class="trade-item-image">
            <%= cl_image_tag offer.photo.key, height: 300, width: 400, crop: :fill, class: "photo" %>
          </div>
          <div class="middle-container">
            <div class="text-box"><h5> <%= offer.user.first_name %>'s <%= offer.name %> for your <%= request.name %> </h5>
            </div>
          </div>
          <div class="trade-item-image">
            <%= cl_image_tag request.photo.key, height: 300, width: 400, crop: :fill, class: "photo" %>
          </div>
        </div>
        <% end %>
      <% else %>
        <h1>You have no outgoing trades</h1>
    <% end %>
    <hr>
  </div>
</div>

app/views/items/index.html.erb
<div class="container">
  <%# this is the search bar %>
  <div class="searchBar">
  <%# row justify-content-center %>
    <div class="">
      <%= form_with url: items_path, method: :get, class: "sb_form" do %>
      <%= text_field_tag :query, params[:query], class: "sb_textarea", placeholder: "Search for a specific item"%>
      <%= submit_tag "search", name: "", class: "sb_button" %>
    <% end %>
  </div>
</div>
<%# this is the search bar %>

<div class="row row-cols-1 row-cols-md-3 g-4">
  <% @items.each do |item| %>
    <div class="col">
      <div class="card d-flex">
        <%= link_to item, :action => 'go' do %>
          <div class="item-photo">
            <%= cl_image_tag item.photo.key, height: 300, width: 400, crop: :fill, class: "photo" %>
          </div>

          <div class="card-body">
            <h5 style="font-size:35px;" class="card-title"><%= item.name %></h5>
            <p class="card-text">€<%= item.price %></p>
            <p class="card-text">Owner: <%= item.user.first_name %></p>
          </div>

        <% end %>
      </div>
  </div>
      <% end %>
</div>
</div>

app/views/items/new.html.erb
<%= render "itemform", item: @item %>

app/views/items/show.html.erb
<div class="container">
<div class="show-card mb-3" >
  <div class="row g-0">
    <div class=" col-md-4">
      <%= cl_image_tag @item.photo.key, height: 300, width: 400, crop: :fill %>
    </div>
    <div class="flex-container col-md-4">
      <div class="show-card-body">
        <h2 class="card-title"><%=@item.user.first_name.capitalize%>'s Item For Trade</h2>
        <h3 class="card-title"><%= @item.name %></h3>
        <p class="card-text"><%= @item.description %> </p>
        <p class="card-text">€<%= @item.price %> </p>
        <p class="card-text"><small class="text-body-secondary"> Category: <%= @item.category %></small></p>
      </div>
    </div>
  </div>
</div>

  <br>
  <br>
</div>
<div class="container">
  <% if user_signed_in? %>
    <% if @item.user != current_user %>
      <%= simple_form_for [ @item, @trade] do |f| %>
        <%= f.hidden_field :requested_item_id, value: @item.id %>
        <%= f.input :offered_item_id, collection: Item.where(user_id: current_user)%>
        <div class="buttonFormGlobal">
        <%= f.submit 'make offer!', class: '' %>
        </div>
      <% end %>
    <% else %>
      <p>You cannot make an offer on your own items</p>
    <% end %>
    <% else %>
    <div class="buttonFormGlobal">

    <%= link_to "Login to make an offer!", new_user_session_path, class: "" %>
    </div>

    <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Giveandtake</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>

  <%# this was added by us %>
  <%= render "shared/navbar" %>

  <%# # not sure about the position of these three codes! %>

  <%# #alert-flashes %>
  <%= render "shared/flashes" %>

    <%= yield %>

  <%= render "/shared/footer"  %>

  </body>
</html>

app/views/pages/home.html.erb
<h1>Pages#home</h1>
<p>Find me in app/views/pages/home.html.erb</p>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert" data-controller="flashes" data-flashes-timeout-value="5000">
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert" data-controller="flashes" data-flashes-timeout-value="5000">
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<%# <div class="footer fixed-bottom">
<div class="footer-copyright">
    Give and Take is a project aiming to extend the lifetime of everyday items.
    Our mission is to reduce waste by connecting people through trade.
    Give and Take today!

  </div>
</div> %>


<footer class="new_footer_area bg_color ">
  <div class="new_footer_top ">

        <div class="footer_bg">
          <div class="footer_bg_one"></div>
          <div class="footer_bg_two"></div>
        </div>
      </div>
    </div>
  </div>
  <div class="d-flex justify-content-center"><p>Give and Take connects people to trade everyday items and reduce waste. Join us today!</p></div>
</footer>

app/views/shared/_navbar.html.erb
  <div class="navbar navbar-expand-sm navbar-light navbar-lewagon fixed-top">
    <div class="container">
      <ul class="navbar-nav me-auto">
          <li>
            <%= link_to "/items", class: "navbar-brand me-0" do %>
            <%= image_tag "giveittome.png", class: 'mt-1'  %>
          </li>
        <li>
          <h2>give and take</h2>
        </li>
      </ul>
    <% end %>


    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto">
        <% if user_signed_in? %>

          <li class="nav-item">
            <%= link_to "new item", "/items/new", class: "nav-link" %>
          </li>

          <li class="nav-item">
            
            <%= link_to "profile", "/dashboard", class: "nav-link" %>
          </li>

          <li class="nav-item dropdown">
          <a href="#" class="avatar" id="navbarDropdown" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            <%= image_tag "https://kitt.lewagon.com/placeholder/users/ssaunier", class: "avatar", alt: "dropdown menu" %>
          </a>

            <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
              <%= link_to "Log out", destroy_user_session_path, data: {turbo_method: :delete}, class: "dropdown-item" %>
            </div>
          </li>
        <% else %>
          <li class="nav-item">
          <li>
              <%= link_to "Signup", "/users/sign_up", class: "nav-link" %>
          </li>
          <%# <%= link_to "Create new listing", new_item_path, class: "nav-link"  %>
            <%= link_to "Login", new_user_session_path, class: "nav-link" %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</div>

app/views/shared/_searchbar_html.erb
<form novalidate="novalidate" class="simple_form search" action="/" accept-charset="UTF-8" method="get">
  <div class="search-form-control form-group">
    <input class="form-control string required" type="text" name="search[query]" id="search_query" />
    <button name="button" type="submit" class="btn btn-flat">
      <i class="fas fa-search"></i> Search
    </button>
  </div>
</form>